# Generated by Django 2.1.4 on 2018-12-24 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_heading', models.CharField(max_length=255)),
                ('task_detail', models.TextField()),
                ('address', models.TextField()),
                ('lat', models.CharField(max_length=25)),
                ('lang', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TrackTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('track_field', django.contrib.postgres.fields.jsonb.JSONField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Employee')),
            ],
        ),
    ]
