# Generated by Django 2.1.4 on 2019-02-02 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_authentication',
            name='token',
            field=models.CharField(db_index=True, default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 2, 7, 1, 37, 415478, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
