# Generated by Django 2.1.4 on 2019-02-02 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190202_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracktable',
            name='track_field',
        ),
        migrations.AddField(
            model_name='tracktable',
            name='lang',
            field=models.CharField(default=0.0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracktable',
            name='lat',
            field=models.CharField(default=0.0, max_length=6),
            preserve_default=False,
        ),
    ]
