# Generated by Django 2.1.4 on 2019-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190202_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracktable',
            name='lang',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tracktable',
            name='lat',
            field=models.CharField(max_length=10),
        ),
    ]
